# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Make private key pem file
        run: echo ${PEM_KEY} > ~/AWS_Server.pem
        env:
          PEM_KEY: ${{secrets.AWS_SERVER_PRIVATE_PEM_KEY}}
        
      - name: Access AWS instacse with SSH
        run: |
          ssh -i ~/AWS_Server.pem -p 22 -l ${USER} ${IP}
        env:
          USER: ${{secrets.AWS_SERVER_USER}}
          IP: ${{secrets.AWS_SERVER_IP}}
        
      - name: Remove running docker containers
        run: |
          docker-compose -f ${YML_PATH} down
        env:
          YML_PATH: ${{secrets.AWS_SERVER_DOCKER_COMPOSE_YML}}
        
      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'
      
      - name: Start docker containers
        run: |
          docker-compose -f ${YML_PATH} -d up
        env:
          YML_PATH: ${{secrets.AWS_SERVER_DOCKER_COMPOSE_YML}}
          
